### ISSUE TITLE
Swift 3.0 dev snapshot build failure

### ISSUE THREAD

**Issue by mikehenson** [SwiftGL/SwiftGL#3]
I'm using the Swift development snapshot on Ubuntu 15.10:

Swift version 3.0-dev (LLVM a7663bb722, Clang 4ca3c7fa28, Swift 1c2f40e246)
Target: x86_64-unknown-linux-gnu

When I try to build the HelloWorld demo app, build fails with (snippet only, for reference):

`SIL verification failed: entry point has wrong number of arguments: entry->bbarg_size() == ti->getParameters().size()
In function:
// SwiftGLmath.any <A where A: SwiftGLmath.BooleanVectorType, A.Generator.Element: Swift.BooleanType, A.Element == Swift.Bool> (A) -> A.Element
sil `

This does look like SwiftGL has surfaced a bug in the 3.0 snapshot's SIL generator or verification. I'm reporting it here first in case you've got more context or have already filed a Swift bug for it.

**Comment by AE9RB** [comment]
I gave the bug to Apple a couple weeks ago. https://bugs.swift.org/browse/SR-622

You can comment out the offending functions until they fix it. The demos weren't affected last I looked.

**Comment by luxvio** [comment]
Same here ... my solution was `rm -rf`'ing the whole math and res modules (because ATM I didn't need/wanted them imported) and removing the corresponding targets from `Package.swift`.    
    
So far I'm quite impressed how pleasant, trouble-free and ergonomic is working with GL in Swift through this library :smile: , thank you !

**Comment by AE9RB** [comment]
The OpenGL loader is the very first thing I wrote in Swift. I'm glad you like it.

I was going to split things up but then they dropped the package manager from 2.2, and I can't jump to 3.0 because of this bug, so I'm waiting.

**Comment by AE9RB** [comment]
This was fixed in the last snapshot.
