### ISSUE TITLE
expected argument type 'GLFWkeyfun!'

### ISSUE THREAD

**Issue by kelvin13** [SwiftGL/SwiftGL#4]
I’m following the tutorial and I can’t get past the `error: cannot convert value of type '(OpaquePointer, Int32, Int32, Int32, Int32) -> ()' to expected argument type 'GLFWkeyfun!'
glfwSetKeyCallback(window, keyCallback)` problem when I try to do the `hello_window2` example.

I used the function 

    func keyCallback(window: OpaquePointer, key: Int32, scancode: Int32, action: Int32, mode: Int32)
    {
        if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS) {
            glfwSetWindowShouldClose(window, GL_TRUE)
        }
    }

exactly as show, with and without the `typealias GLFWkeyfun = (COpaquePointer, Int32, Int32, Int32, Int32) -> Void` part.

I’m on Swift 3, and I was able to port the entire SGLOpenGL package to Swift 3, but I don’t know how to fix the key callback problem.

**Comment by kelvin13** [comment]
I FOUND THE PROBLEM

GLFW wanted a `@convention(c) ((Optional<OpaquePointer>, Int32, Int32, Int32, Int32)) -> ()`. So you have to change the `OpaquePointer` to an optional `OpaquePointer` in the function definition.

**Comment by jkolb** [comment]
Tutorial isn't update yet, but this project should be updated, and the SwiftGL/examples are almost completely migrated to Swift 3.1.
